# Spring Boot Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    cz.ivosahlik: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password:
  application:
    name: mydb
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

api:
  cors:
    allowedOrigins: http://localhost:4200
